config/routes.rb
Brunhilde::Application.routes.draw do |map|
  resources :computers do
    member do
      post :sort
      post :add_package
      post :add_configuration
      post :remove_configuration
    end
    resources :applied_configurations
  end

  resources :configurations do
    member do
      post :sort
      post :add_package
      post :remove_package
    end
    resources :applied_packages
  end
  resources :packages do
    resources :install_validations do
      resources :install_validation_reactions
    end
  end
  resources :user_sessions
  resources :users
  match ':controller/:action/:id.:format'
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  has_many  :applied_configurations,  :dependent => :destroy
  has_many  :applied_packages,        :order => :position,
                                      :dependent => :destroy
  has_many  :computers,               :through => :applied_configurations
  has_many  :packages,                :through =>:applied_packages,
                                      :order => :position
  belongs_to :host_computer,          :class_name => "Computer"
  belongs_to :owner,                  :class_name => "User"
  
  attr_accessor :applied_package_list
  
  validates_presence_of               :platform, 
                                      :name
  validates_uniqueness_of             :name
  validate                            :host_computer_is_only_related_computer_if_defined
  validates_inclusion_of              :platform, :in => PLATFORMS
  validate                            :applied_package_list_integrity_test
  validate                            :applied_packages_are_in_stage_order
  
  after_save :sort, :if => :applied_package_list
  
  scope :non_hosted, where(:host_computer_id => nil) 
                                              
  def self.search(query)
     if !query.to_s.strip.empty?
        tokens = query.split.collect {|c| "%#{c.downcase}%"}
        
        configurations = non_hosted.find_by_sql(["select c.* from configurations c where #{ (["(lower(c.name) like ?)"] * tokens.size).join(" and ") } order by c.name desc", *(tokens).sort])
        configurations.delete_if { |c| c.host_computer }
     else
        []
     end
  end
  def prescript_packages
    packages.clone.delete_if{ |p| p.deployment_stage != 0}
  end
  def postscript_packages
    packages.clone.delete_if{ |p| p.deployment_stage != 1}
  end
  
  private
  def host_computer_is_only_related_computer_if_defined
    if host_computer
      if computers.size == 0
        errors.add(:host_computer, "Configuration is hosted, but has no related computers")
      end
      if computers.size > 1
        errors.add(:host_computer, "Configuration is hosted, but is related to more than one computer")
      end
      if computers.size == 1 && computers[0] != host_computer
        errors.add(:host_computer, "Configuration is hosted, but is related to the wrong computer")
      end
    end 
  end
  def applied_package_list_integrity_test
    if @applied_package_list
      current_stage = 0
      @applied_package_list.each do |id|
        errors.add(:sorting, "Invalid object in sort list (#{id})") unless AppliedPackage.exists?(id) && AppliedPackage.find(id).configuration == self
        ap = AppliedPackage.find(id)
        errors.add(:sorting, "The sort request would put a stage #{ap.package.deployment_stage} object in stage #{current_stage}") if ap.package.deployment_stage < current_stage
        current_stage = ap.package.deployment_stage
      end
      applied_packages.each do |ap|
        errors.add(:sorting, "Object missing from the sort list (#{id})") unless @applied_package_list.include?(ap.id)
      end
    
    end
  end
  def applied_packages_are_in_stage_order
    current_stage = 0
    applied_packages.each { |ap|
      errors.add(:applied_packages, "There is a stage #{ap.package.deployment_stage} object in stage #{current_stage}") if ap.package.deployment_stage < current_stage
      current_stage = ap.package.deployment_stage
    }
  end
  def sort
    applied_package_list.each_with_index do | f, i |
      pkg = AppliedPackage.find(f)
      pkg.position = i
      pkg.save
    end
  end
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController
  before_filter :set_current_tab
  
  # GET /configurations
  # GET /configurations.xml
  def index
    if params[:query]
      @configurations = Configuration.search(params[:query])
      @query = params[:query]
    else
      @configurations = Configuration.find_all_by_host_computer_id(nil)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @configurations }
      format.json { render :json => @configurations }
    end
  end

  # GET /configurations/1
  # GET /configurations/1.xml
  def show
    @configuration = Configuration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @configuration }
    end
  end

  # GET /configurations/new
  # GET /configurations/new.xml
  def new
    @configuration = Configuration.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @configuration }
    end
  end

  # GET /configurations/1/edit
  def edit
    @configuration = Configuration.find(params[:id])
  end

  # POST /configurations
  # POST /configurations.xml
  def create
    @configuration = Configuration.new(params[:configuration])
    @configuration.owner = current_user
    respond_to do |format|
      if @configuration.save
        flash[:notice] = 'Configuration was successfully created.'
        format.html { redirect_to(@configuration) }
        format.xml  { render :xml => @configuration, :status => :created, :location => @configuration }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @configuration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /configurations/1
  # PUT /configurations/1.xml
  def update
    @configuration = Configuration.find(params[:id])

    respond_to do |format|
      if @configuration.update_attributes(params[:configuration])
        flash[:notice] = 'Configuration was successfully updated.'
        format.html { redirect_to(@configuration) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @configuration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /configurations/1
  # DELETE /configurations/1.xml
  def destroy
    @configuration = Configuration.find(params[:id])
    @configuration.destroy

    respond_to do |format|
      flash[:notice] = "Configuration was successfully destroyed"
      format.html { redirect_to(configurations_url) }
      format.xml  { head :ok }
    end
  end
  
  def sort
    @configuration = Configuration.find(params[:id])
    @configuration.applied_packages.each do |applied_package|
      applied_package.position = params['item'].index(applied_package.id.to_s) + 1
      applied_package.save
    end
    render :nothing => true
  end
  
  private
    def set_current_tab
      @current_tab = "configurations"
    end
end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/views/configurations/_applied_packages.erb
<ul id="applied-package-list" class="sortable-list">
	<% @configuration.applied_packages.each do |ap| %>
		<li id="item_<%= ap.id %>" class="<%= cycle("even", "odd") %>">
			<%= ap.package.name %>
			<%= link_to 	'X',
			 				configuration_applied_package_url(@configuration, ap),
							:confirm 	=> 'Are you sure?',
							:remote 	=> true ,
							:method 	=> :delete,
							:class		=> "delete_applied_package" %>
			<span class="handle">[handle]</span>
		</li>
	<% end %>
</ul>

<% content_for :javascript do %>
	<%= javascript_tag do %>
		$('.delete_applied_package')
			.live("ajax:success", function(xhr, data, status) {
				$(this).parent().hide();
			});
		$("#applied-package-list").sortable({
			axis:'y',
			dropOnEmpty:false,
			handle:'.handle',
			cursor:'crosshair',
			items:'li',
			opacity:0.4,
			scroll:true,
			update: function(){
				$.ajax({
					type: 'post',
					data: $('#applied-package-list').sortable('serialize'),
					dataType: 'script',
					complete: function(request){
						$('#applied-package-list').effect('highlight');
					},
					url: '/configurations/<%=@configuration.id-%>/sort'
				})
			}
		})
	<% end %>
<% end %>

app/views/configurations/_select_package_rb.erb
<div style="padding: 5px; height: 200px; width: 300px; background: #FFF">
	<p style="align: right">
		<%= link_to_close_redbox("close") %>
	</p>
	<div style="height: 190px; overflow: auto">
		<%= form_tag(	add_package_configuration_url(@configuration), :remote => true) do %>
			<%unless @packages && @packages.size > 0 %>
				<%= text_field_tag :query %><br />
				<%= submit_tag "Search"%>
			<% else %>
				<%= select_tag :package_id, options_from_collection_for_select(@packages, 'id', 'name') %><br />
				<%= submit_tag "Add" %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/configurations/edit.html.erb
<h1>Editing configuration</h1>

<%= form_for(@configuration) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
	
	<p>
		<%= f.label :platform %><br />
		<table>
		<% PLATFORMS.each do |platform| %>
			<tr>
				<td><%= f.radio_button(:platform, platform)%></td>
				<td><%= f.label(:platform, platform) %></td>
			</tr>
		<% end %>
		</table>
	</p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes, :rows => 2 %>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @configuration %> |
<%= link_to 'Back', configurations_path %>

app/views/configurations/index.html.erb
<h1>Listing configurations</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @configurations.each do |configuration| %>
  <tr class="<%= cycle("even", "odd") %>">
    <td><%=h configuration.name %></td>
    <td><%= link_to 'Show', configuration %></td>
    <td><%= link_to 'Edit', edit_configuration_path(configuration) %></td>
    <td><%= link_to 'Destroy', configuration, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New configuration', new_configuration_path %>

app/views/configurations/new.html.erb
<h1>New configuration</h1>

<%= form_for(@configuration) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
	<p>
		<%= f.label :platform %><br />
		<table>
		<% PLATFORMS.each do |platform| %>
			<tr>
				<td><%= f.radio_button(:platform, platform)%></td>
				<td><%= f.label(:platform, platform) %></td>
			</tr>
		<% end %>
		</table>
	</p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', configurations_path %>

app/views/configurations/show.html.erb
<p>
  <b>Name:</b>
  <%=h @configuration.name %>
</p>

<p>
  <b>Notes:</b>
  <%=h @configuration.notes %>
</p>

<p>
	<b>Packages:</b>
</p>
<p>
	<button id="addPackage" value="Add Package...">Add Package...</button>
</p>
<div id="applied_packages">
	<%= render :partial => "applied_packages"%>
</div>


<p>
	<b>Postscript Packages:</b>
</p>
<%= link_to 'Edit', edit_configuration_path(@configuration) %> |
<%= link_to 'Back', configurations_path %>

<div id="packageSearchDialog" title="Search for Packages">
	<%= form_tag( "/packages.json", :remote => true, :method => :get, :id => "package_search_form" ) do %>
		<%= text_field_tag :query%> 
		<%= submit_tag "Search..."%>
	<% end %>
</div>
<div id="packageSelectDialog" title="Select a Package">
	<%= form_for([@configuration, AppliedPackage.new], :format => :json, :remote => true) do |f|%>
		<%= f.select :package_id, {}, :id => 'packageSelect' %><br />
		<%= f.submit "Add" %>
	<% end %>
</div>

<% content_for :javascript do %>
	<%= javascript_tag do %>
		
		$(document).ready(function() {
			$('#packageSearchDialog').dialog({modal:true, autoOpen:false});
			$('#packageSelectDialog').dialog({modal:true, autoOpen:false});
		})
		
		jQuery("#package_search_form")
			.live("ajax:success", function(xhr, data, status) {
				packages = $.parseJSON(data);
				$.each( packages, function(index, package) {
					$('#packageSelectDialog form select').append("<option value='" + package.package.id + "'>" + package.package.name + "</option>");
				});
				$('#packageSearchDialog').dialog('close');
				$('#packageSelectDialog').dialog('open');

			})
		
		jQuery("#packageSelectDialog form")
			.live("ajax:success", function(xhr, data, status) {
				applied_package = $.parseJSON(data).applied_package;
				
				li = "<li id='item_"+ applied_package.id +"'>" + applied_package.package.name + " <a href='/configurations/<%= @configuration.id %>/applied_packages/" + applied_package.id + "' class='delete_applied_package' data-confirm='Are you sure?' data-method='delete' data-remote='true' rel='nofollow'>X</a><span class='handle'>[handle]</span></li>"
				$('#packageSelectDialog').dialog('close');
				$('#applied_packages ul').append(li);
			})
		$('#addPackage').click(function() {
			$('#packageSearchDialog').dialog('open');
		})
	<% end %>
<% end %>
	