config/routes.rb
Brunhilde::Application.routes.draw do |map|
  resources :computers do
    member do
      post :sort
      post :add_package
      post :add_configuration
      post :remove_configuration
    end
    resources :applied_configurations
  end

  resources :configurations do
    member do
      post :sort
      post :add_package
      post :remove_package
    end
    resources :applied_packages
  end
  resources :packages do
    resources :install_validations do
      resources :install_validation_reactions
    end
  end
  resources :user_sessions
  resources :users
  match ':controller/:action/:id.:format'
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
end

app/models/computer.rb
class Computer < ActiveRecord::Base
  has_many :applied_configurations, :order        => :position,
                                    :dependent    => :destroy
  has_many :configurations,         :through      => :applied_configurations,
                                    :order        => :position
  has_many :hosted_configurations,  :class_name   => "Configuration",
                                    :foreign_key  => :host_computer_id,
                                    :dependent    => :destroy
  belongs_to :owner, :class_name => "User"
  attr_accessor :applied_configuration_list
  
  validates_presence_of :mac_address, :platform
  validates_uniqueness_of :mac_address
  validates_associated :applied_configurations
  validates_inclusion_of :platform, :in => PLATFORMS
  validate :applied_configuration_list_integrity_test
  after_save :sort, :if => :applied_configuration_list
  
  PRESCRIPT_PHASE = 0
  POSTSCRIPT_PHASE = 1
  
  def self.search(query)
     if !query.to_s.strip.empty?
        tokens = query.split.collect {|c| "%#{c.downcase}%"}
        computers = find_by_sql(["select c.* from computers c where #{ (["(lower(c.name) like ?)"] * tokens.size).join(" and ") } order by c.name desc", *(tokens).sort])
     else
        []
     end
  end
  def postscript
    if (self.platform == "PC")
      pc_postscript_prefix + pc_script_body(POSTSCRIPT_PHASE) + pc_postscript_suffix
    elsif (self.platform == "Mac")
      mac_postscript_prefix + mac_script_body(POSTSCRIPT_PHASE) + mac_postscript_suffix
    end
  end
  def prescript
    if (self.platform == "PC")
      pc_prescript_prefix + pc_script_body(PRESCRIPT_PHASE) + pc_prescript_suffix
    elsif (self.platform == "Mac")
      mac_header + mac_script_body(PRESCRIPT_PHASE) + mac_prescript_suffix
    end
  end
  def packages
    package_list = Array.new
    configurations.each do |configuration|
      package_list = package_list + configuration.packages
    end
    return package_list
  end
  
  private
  
  def pc_prescript_prefix
    prefix = [
                "REM *****************************************",
                "REM *                                       *",
                "REM *         Brunhilde Prescript          *",
                "REM *      Jason Gignac, Arturo Martinez    *",
                "REM *       NOTE: Dynamically Generated     *",
                "REM *                                       *",
                "REM *****************************************",
                "REM Generation Date: " + Time.now.strftime("%m/%d/%Y %I:%M:%S %p %Z"),
                "REM Target:          " + self.mac_address,
                "",
                ":prefix",
                "REM Load Environment Variables",
                "REM --Reads each line from var.txt, and executes it",
                "CALL var.bat",
                "",
                "NET USE S: %BRUNHILDE_REPO_SRV% P@scpcs1nst /USER:PEROOT\\svc-eduhassatinst001",
                "SET BRUNHILDE_REPO_SRV=S:"
              ]
  end
  def pc_prescript_suffix
    suffix = [
        ":suffix",
        "mkdir c:\\brunhilde",
        "copy /y x:\\brunhilde\\var.txt c:\\brunhilde",
	"copy /y x:\\brunhilde\\var.bat c:\\brunhilde",
        "copy /y x:\\brunhilde\\postscript.bat c:\\brunhilde",
        "Shutdown -r -t 5"
      ]
  end
  def pc_postscript_prefix
    
    prefix = [
                  "REM *****************************************",
                  "REM *                                       *",
                  "REM *         Brunhilde Postscript          *",
                  "REM *      Jason Gignac, Arturo Martinez    *",
                  "REM *       NOTE: Dynamically Generated     *",
                  "REM *                                       *",
                  "REM *****************************************",
                  "REM Generation Date: " + Time.now.strftime("%m/%d/%Y %I:%M:%S %p %Z"),
                  "REM Target:          " + self.mac_address,
                  "",
                  ":prefix",
                  "REM Load Environment Variables",
                  "REM --Reads each line from var.txt, and executes it",
                  "CALL c:\\brunhilde\\var.bat",
                  "",
                  "REM Set up BRUNHILDEPHASE variable",
                  "if [%BRUNHILDEPHASE%]==[] (",
                  set_environment_variable("BRUNHILDEPHASE","0"),
                  "SET BRUNHILDEPHASE=0",
                  ")",
                  "",
                  "REM Wait until machine responds to ping before going on.",
                  ":pingwait",
                  "setLocal EnableDelayedExpansion",
                  "ping 10.133.16.35 | find \"Reply\" > nul",
                  "ping 10.133.16.35 | find \"Reply\" > nul",
                  "ping 10.133.16.35 | find \"Reply\" > nul",
                  "if errorlevel 1 (",
                  "echo Waiting...",
                  "goto :pingwait)",
                  "NET USE S: %BRUNHILDE_REPO_SRV% P@scpcs1nst /USER:PEROOT\\svc-eduhassatinst001",
                  "if errorlevel 1 (",
                  "echo Netowrk Not found",
                  "goto :pingwait)",
                  "SET BRUNHILDE_REPO_SRV=S:",
                  "goto :phase%BRUNHILDEPHASE%"]
  end
  def pc_postscript_suffix
    suffix = [
                ":suffix",
                "cd \\",
                set_environment_variable("BRUNHILDEPHASE", nil),
                "REG delete \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce\" /v BrunhildePost /f",
                "echo Script Completed",
                "reg delete \"HKLM\\software\\Microsoft\\windows nt\\currentversion\\winlogon\" /v DefaultPassword /f",
                "reg add \"HKLM\\software\\microsoft\\windows nt\\currentversion\\winlogon\" /v AutoadminLogon /t REG_SZ /d 0 /f",
                "reg add \"HKLM\\software\\microsoft\\windows nt\\currentversion\\winlogon\" /v DisableCAD /t REG_DWORD /d 0 /f",
                "del /f /q c:\\Brunhilde\\*.vbs",
                "rmdir /S /Q c:\\Cache",
                "Shutdown -r -t 5",
                "REM Script Complete"
                
                ]
  end
  def pc_script_body(deployment_phase)
    script_for_packages = Array.new
    phase = 0
    self.packages.each do |package|
      execution=package.script(deployment_phase)
      if(execution.length > 0)
        script_for_packages << "REM Phase #{phase}: " + package.name
        script_for_packages << ":phase#{phase}"
        script_for_packages << set_environment_variable("BRUNHILDEPHASE",(phase + 1).to_s)
        script_for_packages = script_for_packages + execution
        script_for_packages << "echo Completed phase #{phase}"
        script_for_packages << ""
        phase = phase + 1
      end
    end
    return script_for_packages
  end
  def set_environment_variable(name, value)
    if value
      "REG ADD \"HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\Environment\" /v #{name} /t REG_SZ /d \"#{value}\" /f"
    else
      "REG delete \"HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\Environment\" /v #{name} /f"
    end
  end
  
  def mac_header
    header = [
                "#!/bin/bash",
                "# *****************************************",
                "# *                                       *",
                "# *         Brunhilde Prescript          *",
                "# *      Jason Gignac, Arturo Martinez    *",
                "# *       NOTE: Dynamically Generated     *",
                "# *                                       *",
                "# *****************************************",
                "# Generation Date: " + Time.now.strftime("%m/%d/%Y %I:%M:%S %p %Z"),
                "# Target:          " + self.mac_address,
                "if ! test $BRUNHILDEPHASE",
                "then",
                "BRUNHILDEPHASE=1",
                "fi",
                ""
    ]
  end
  def mac_prefix
    prefix = [
                "# PREFIX",
                "# Load Environment Variable from mac_var.txt",
                "# (Execute mac_var.txt)",
                "source /brunhilde/mac_var.txt",
                "echo REPO: $BRUNHILDE_REPO_SRV",
                "echo IMAGE: $BRUNHILDE_IMAGE_SRV",
                "# Wait until machine responds to ping before going on.",
                "while ping -c 1 -w 15 google.com &> /dev/null",
                "do",
                "echo Waiting for ping to succeed...",
                "done",
                "# Mount the Software Repository",
                "mkdir /brunhilde/softwarerepository",
                "mount_afp afp://PEROOT\\\\svc-eduhassatinst001:P%40scpcs1nst@$BRUNHILDE_REPO_SRV /brunhilde/softwarerepository",
                "BRUNHILDE_REPO_SRV=/brunhilde/softwarerepository",
                "",
                "# Set up BRUNHILDEPHASE variable",
                
              ]
  end
  def mac_prescript_suffix
    suffix = [
        "# SUFFIX",
        "mkdir /Volumes/InstaDMG/brunhilde",
        "cp /brunhilde/mac_var.txt /Volumes/InstaDMG/brunhilde/",
        "cp /brunhilde/postscript.bash /Volumes/InstaDMG/brunhilde/",
        "# shutdown -r now"
      ]
  end
  def mac_postscript_suffix
  end
  def mac_script_body(deployment_phase)
    script_for_packages = Array.new
    phase = 0
    if (deployment_phase = PRESCRIPT_PHASE) then
      script_for_packages = script_for_packages + add_mac_function("Prefix", mac_prefix, phase)
    end
    self.packages.each do |package|
      execution=package.script(deployment_phase)
      if(execution.length > 0)
        phase = phase + 1
        script_for_packages = script_for_packages + add_mac_function( package.name,
                                                                      execution, 
                                                                      phase)
      end
    end
    script_for_packages << "phase0"
    puts "Phase : #{phase}"
    if (phase > 0) then

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_filter :set_current_tab
  # GET /computers
  # GET /computers.xml
  def index
    if params[:query]
      @computers = Computer.search(params[:query])
      @query = params[:query]
    else
      @computers = Computer.all
    end
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @computers }
    end
  end

  # GET /computers/1
  # GET /computers/1.xml
  def show
    @computer = Computer.find(params[:id])  
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @computer }

    end
  end

  # GET /computers/new
  # GET /computers/new.xml
  def new
    @computer = Computer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @computer }
    end
  end

  # GET /computers/1/edit
  def edit
    @computer = Computer.find(params[:id])
  end

  # POST /computers
  # POST /computers.xml
  def create
    @computer = Computer.new(params[:computer])
    @computer.owner = current_user
    respond_to do |format|
      if @computer.save
        flash[:notice] = 'Computer was successfully created.'
        format.html { redirect_to(@computer) }
        format.xml  { render :xml => @computer, :status => :created, :location => @computer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @computer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /computers/1
  # PUT /computers/1.xml
  def update
    @computer = Computer.find(params[:id])
    
    respond_to do |format|
      if @computer.update_attributes(params[:computer])
        flash[:notice] = 'Computer was successfully updated.'
        format.html { redirect_to(@computer) }
        format.xml  { head :ok }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @computer.errors, :status => :unprocessable_entity }
        format.json { render :json => @computer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.xml
  def destroy
    @computer = Computer.find(params[:id])
    @computer.destroy

    respond_to do |format|
      flash[:notice] = 'Computer was successfully destroyed'
      format.html { redirect_to(computers_url) }
      format.xml  { head :ok }
    end
  end
  
  # Refactor these
  private
    def set_current_tab
      @current_tab = "computers"
    end
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_applied_configurations.erb
<table id="applied-configuration-list" class="config_package_table">
	<% @computer.applied_configurations.each do |ac| %>	
		<tr id="<%=ac.class.to_s.downcase %>_<%= ac.id %>" class="applied_configuration">
			<th>
				<%= ac.configuration.name %> 
				<%= link_to 	'X',
		 						computer_applied_configuration_url(@computer, ac),
								:confirm 	=> 'Are you sure?',
								:remote 	=> true,
								:method 	=> :delete,
								:class		=> "delete_link" %>
			</th>
			<td>
				Prescript:
				<ul>
					<% ac.configuration.prescript_packages.each do |p| %>
						<li><%= p.name %></li>
					<% end %>
				</ul>
			</td>
			<td>
				Postscript:
				<ul>
					<% ac.configuration.postscript_packages.each do |p| %>
						<li><%= p.name %></li>
					<% end %>
				</ul>
			</td>
		</tr>
	<% end %>
</table>

app/views/computers/_select_configuration.erb
<div style="padding: 5px; height: 200px; width: 300px; background: #FFF">
	<p style="align: right">
		<%= link_to_close_redbox("close") %>
	</p>
	<div style="height: 190px; overflow: auto">
		<%= form_tag(	add_configuration_computer_url(@computer),
						:remote => true) do %>
			<%unless @configurations && @configurations.size > 0 %>
				<%= text_field_tag :query %><br />
				<%= submit_tag "Search"%>
			<% else %>
				<%= select_tag :configuration_id, options_from_collection_for_select(@configurations, 'id', 'name') %><br />
				<%= submit_tag "Add" %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/computers/_select_package.html.erb
<div style="padding: 5px; height: 200px; width: 300px; background: #FFF">
	<p style="align: right">
		<%= link_to_close_redbox("close") %>
	</p>
	<div style="height: 190px; overflow: auto">
		<%= form_tag(add_package_computer_url(@computer),
					:remote => true) do %>
			<%unless @packages && @packages.size > 0 %>
				<%= text_field_tag :query %><br />
				<%= submit_tag "Search"%>
			<% else %>
				<%= select_tag :package_id, options_from_collection_for_select(@packages, 'id', 'name') %><br />
				<%= submit_tag "Add" %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/computers/edit.html.erb
<h1>Editing computer</h1>

<%=form_for(@computer) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :mac_address %><br />
    <%= f.text_field :mac_address %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  	<p>
		<%= f.label :platform %><br />
		<table>
		<% PLATFORMS.each do |platform| %>
			<tr>
				<td><%= f.radio_button(:platform, platform)%></td>
				<td><%= f.label(:platform, platform) %></td>
			</tr>
		<% end %>
		</table>
	</p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @computer %> |
<%= link_to 'Back', computers_path %>

app/views/computers/index.html.erb
<h1>Listing computers</h1>

<table>
  <tr>
    <th>Mac address</th>
    <th>Name</th>
    <th>Platform</th>
  </tr>

<% @computers.each do |computer| %>
  <tr class="<%= cycle("even", "odd") %>">
    <td><%=h computer.mac_address %></td>
    <td><%=h computer.name %></td>
    <td><%=h computer.platform %></td>
    <td><%= link_to 'Show', computer %></td>
    <td><%= link_to 'Edit', edit_computer_path(computer) %></td>
    <td><%= link_to 'Destroy', computer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New computer', new_computer_path %>

app/views/computers/new.html.erb
<h1>New computer</h1>

<%= form_for(@computer) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :mac_address %><br />
    <%= f.text_field :mac_address %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  	<p>
		<%= f.label :platform %><br />
		<table>
		<% PLATFORMS.each do |platform| %>
			<tr>
				<td><%= f.radio_button(:platform, platform)%></td>
				<td><%= f.label(:platform, platform) %></td>
			</tr>
		<% end %>
		</table>
	</p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', computers_path %>

app/views/computers/show.html.erb
<div class="editInPlace">
  <b>Mac address:</b>
  <div class="editInPlace"><%=h @computer.mac_address %></div>
</div>

<div class="editInPlace">
  <b>Name:</b>
  <div class="editInPlace"><%=h @computer.name %></div>
</div>

<div>
  <b>Platform:</b>
  <div class="editInPlace"><%=h @computer.platform %></div>
</div>

<div>
	<b>Configurations:</b>
</div>
<div>
	<%= link_to( 	"Add...", 
					"#",
					:id => "add_ac")%>
</div>

<div id="applied_configurations">
	<%= render :partial => "applied_configurations"%>
</div>

<%= link_to 'Edit', edit_computer_path(@computer) %> |
<%= link_to 'Back', computers_path %>
<div id="new_ac_form" class="jqmWindow">
	<a href="#" class="jqmClose">X</a>
	<div id="tabs">
	    <ul>
	        <li><a href="<%= new_computer_applied_configuration_path(@computer, :search_for => "configurations") %>"><span>Configurations</span></a></li>
	        <li><a href="<%= new_computer_applied_configuration_path(@computer, :search_for => "packages") %>"><span>Packages</span></a></li>
	    </ul>
	    <div id="configurations-tab">
		</div>
		<div id="packages-tab">
		</div>
	</div>
</div>
		



<% content_for :javascript do %>

	<%= javascript_tag do %>
		// sortable applied_configurations
		jQuery(document).ready(function(){
		    $('#applied-configuration-list').children().sortable({
				axis: 'y',
				containment: 'parent',
				cursor: 'crosshair',
				scroll: true,
				opacity: 0.4,
				update: function(){
					serialized_sort = $('#applied-configuration-list')
										.children()
										.sortable(	'serialize',
														{key:'computer[applied_configuration_list][]'})
			    	jQuery.ajax({
						type: 		'put', 
			           	data: 		serialized_sort + '&id=<%=@computer.id-%>', 
			           	dataType: 	'script', 
			           	success: 	function(request){
			            	$('#applied-configuration-list').effect('highlight');
			           	},
			           	url: '<%= computer_path(@computer, :format => :xml) %>'
					})
				}
			})
		})
	<% end %>
	
	<%= javascript_tag do %>
		// add new applied_configuration behaviour to the 'add' link
		jQuery(document).ready(function(){
			div = jQuery('.jqmWindow')
			div.jqm({
				trigger:	'a#add_ac'
			});
			
			$("#tabs").tabs();
		})
	<% end %>		
	
<% end %>