config/routes.rb
Brunhilde::Application.routes.draw do |map|
  resources :computers do
    member do
      post :sort
      post :add_package
      post :add_configuration
      post :remove_configuration
    end
    resources :applied_configurations
  end

  resources :configurations do
    member do
      post :sort
      post :add_package
      post :remove_package
    end
    resources :applied_packages
  end
  resources :packages do
    resources :install_validations do
      resources :install_validation_reactions
    end
  end
  resources :user_sessions
  resources :users
  match ':controller/:action/:id.:format'
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
end

app/models/install_validation.rb
require 'csv'
class InstallValidation < ActiveRecord::Base
  belongs_to    :package
  has_many      :install_validation_reactions
  acts_as_list  :scope => :package
  validates_presence_of   :package, :success_value, :rule_type, :rule_parameter
  validates_inclusion_of :rule_type, :in => RULE_TYPES
  accepts_nested_attributes_for :install_validation_reactions, :allow_destroy => true
  
  def self.rule_types
    return RULE_TYPES
  end
  def self.csv_headers
    csv_string = String.new
    csv_string << ["rule_type", "rule_parameter", "success_value"].to_csv
    return csv_string
  end
   def to_csv
    csv_string = String.new
    csv_string << ["TEST", rule_type, rule_parameter, success_value].to_csv
    return csv_string.sub!("\n", "")
  end
end 

app/controllers/install_validations_controller.rb
class InstallValidationsController < ApplicationController
  before_filter :set_current_tab
  before_filter :atify_package
  def index
    @install_validations = @package.install_validations

    respond_to do |format|
      format.json { render :json => @install_validations}
      format.xml  { render :xml => @install_validations }
    end
  end

  # GET /install_validations/1
  # GET /install_validations/1.xml
  def show
    @install_validation = InstallValidation.find(params[:id])
    raise ActiveRecord::RecordNotFound unless @install_validation.package == @package
    respond_to do |format|
      format.html { render :partial => "show_iv_row"}
      format.json  { render :json => @install_validation }
      format.xml  { render :xml => @install_validation }
    end
  end

  # GET /install_validations/new
  # GET /install_validations/new.xml
  def new
    @install_validation = InstallValidation.new
    @install_validation.install_validation_reactions << InstallValidationReaction.new
    @install_validation.install_validation_reactions << InstallValidationReaction.new
    @install_validation.install_validation_reactions << InstallValidationReaction.new
    
    respond_to do |format|
      if(request.xhr?)
        format.html { render :partial => "new_iv_row"}
      end
      format.json  { render :json => @install_validation }
      format.xml  { render :xml => @install_validation }
    end
  end
  
  def edit
    @install_validation = InstallValidation.find(params[:id])
    render :partial => "edit_iv_row"
  end
  
  def update
    @install_validation = InstallValidation.find(params[:id])
    respond_to do |format|
      if @install_validation.update_attributes(params[:install_validation])
        flash[:notice] = 'Validation was successfully updated.'
        format.html { render :partial => "show_iv_row" }
      else
        format.json { render :json => @install_validation.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @install_validation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # POST /install_validations
  # POST /install_validations.xml
  def create
    @install_validation = InstallValidation.new(params[:install_validation])
    @install_validation.package_id = @package.id
    respond_to do |format|
      if @install_validation.save
        if(request.xhr?)
          format.html { render :partial => "show_iv_row"}
        end
        format.json  { render :json => @install_validation, :status => :created, :location => package_install_validations_path(@package, @install_validation.id) }
        format.xml  { render :xml => @install_validation, :status => :created, :location => package_install_validations_path(@package, @install_validation.id) }
      else
        format.json { render :json => @install_validation.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @install_validation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /install_validations/1
  # DELETE /install_validations/1.xml
  def destroy
    @install_validation = InstallValidation.find(params[:id])
    raise ActiveRecord::RecordNotFound unless @install_validation.package == @package
    @install_validation.destroy

    respond_to do |format|
      if request.xhr?
        format.js
      end
      format.json { head :ok}
      format.xml  { head :ok }
    end
  end

  private
  def set_current_tab
    @current_tab = "packages"
  end
  def atify_package
    @package = Package.find(params[:package_id])
  end
end

app/views/install_validations/_edit_iv_row.erb
<tr id="edit_iv_row_<%= @install_validation.id %>" class="edit_iv_row">
	<%= form_for([@package, @install_validation], :remote => true) do |f| %>
		<td>
		
			There 
			<%= f.select( :success_value, [["is", true],["is not", false]]) %>
			<%= f.select( :rule_type, DESCRIPTION_FOR_RULE_TYPE.map{ |value, display| [display + "...", value] } ) %>
			<%= f.text_field( :rule_parameter)%>
			<%= f.submit( "Save")%></td>
		</td>
		<td></td>
		<td><%= f.submit( "Save")%></td>
	<% end %>
	<td><%= link_to("Cancel", package_install_validation_path(@package, @install_validation), :remote => true, :class => "cancel_edit_install_validation", :id => @install_validation.id) %></td>
</tr>

app/views/install_validations/_new_iv_row.erb
<tr id="new_iv_row" >
	<td>
		
		<%= form_for([@package, @install_validation], :remote => true) do |f| %>
		
			<div>
				There <%= f.select( :success_value, [["is", true],["is not", false]]) %>
				<%= f.select( :rule_type, 
						DESCRIPTION_FOR_RULE_TYPE.map{ |value, display| [display + "...", value] } 
				) %>
				<%= f.text_field( :rule_parameter)%>
			</div>
			<div>
				<%= f.fields_for :install_validation_reactions do |ivr|%>
					<%= render "install_validation_reaction_fields", :f => ivr %>
				<% end %>
				<%= link_to_add_fields("Add action", f, :install_validation_reactions) %>
			</div>
			<div>
				<%= f.submit( "Save")%>
			</div>
		<% end %>
		<a href="#" id="cancel_new_install_validation">Cancel</a>
	</td>
</tr>

app/views/install_validations/_show_iv_row.erb
<tr class="<%= cycle("even", "odd") %>">
	<td>
		There <%= @install_validation.success_value ? "is" : "is not" %> <%= condition_string(@install_validation) %>
		<br />
	</td>
	<td>
		<table>
			<% @install_validation.install_validation_reactions.each do |ivr| %>
				<tr><td><%= reaction_string(ivr) %></td></tr>
			<% end %>
		</table>
	</td>
	<td><%= link_to 'Edit', edit_package_install_validation_path(@package, @install_validation), :remote => true, :class => "edit_iv_link"  %></td>
	<td><%= link_to 'Destroy', package_install_validation_path(@package, @install_validation), :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => "delete_iv_link" %></td>
</tr>

app/views/install_validations/destroy.js.erb
jQuery("#installvalidation_<%= @install_validation.id %>").hide("blind", {}, 500)

app/views/install_validations/edit.html.erb
<h1>Editing package test</h1>

<% form_for [@package, @package_test] do |f| %>
	<div>
		<table>
			<tr>
				<td>Name</td>
				<td><%= f.text_field(:name)%></td>
			</tr>
			<tr>
				<td>Description</td>
				<td><%= f.text_area(:description)%></td>
			</tr>
			<tr>
				<td>Rule Type</td>
				<td>
					<%= f.radio_button(:rule_type, "ExecRunning")%> ExecRunning (Tests if executable is running)<br />
					<%= f.radio_button(:rule_type, "FileExists")%> FileExists (Tests if a file exists)<br />
					<%= f.radio_button(:rule_type, "Custom")%> Custom (Executes the file at the given path as a test)
				</td>
			</tr>
			<tr>
				<td>Parameter</td>
				<td><%= f.text_field(:rule_parameter)%></td>
			</tr>
			<tr>
				<td>Success Value</td>
				<td><%= f.text_field(:success_value)%></td>
			</tr>
		</table>
	</div>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>
<div>
	<table>
		<tr>
			<td>Action</td>
			<td>Parameter</td>
			<td>Repetitions</td>
		</tr>
		<% @package_test.package_test_reactions.each do |ptr| %>
			<tr>
				<td><%=ptr.command%></td>
				<td><%=ptr.parameter%></td>
				<td><%=ptr.repetitions%></td>
				<td><%= link_to 'Edit', edit_package_test_reaction_path(ptr) %></td>
	    		<td><%= link_to 'Destroy', package_test_reaction_path(ptr), :confirm => 'Are you sure?', :method => :delete %></td>
			</tr>
		<% end %>
	</table>
</div>

<%= link_to 'Show', package_test_path(@package.id, @package_test.id) %> |
<%= link_to 'Back', package_path(@package.id) %>

app/views/install_validations/new.html.erb
<h1>New package</h1>

<% form_for([@package, @package_test], :url => package_tests_path(@package)) do |f| %>
  	<table>
		<tr>
			<td>Name</td>
			<td><%= f.text_field :name%></td>
		</tr>
		<tr>
			<td>Description</td>
			<td><%= f.text_area(:description)%></td>
		</tr>
		<tr>
			<td>Rule Type</td>
			<td>
				<%= f.radio_button(:rule_type, "ExecRunning", :onclick => 'document.getElementById("param_label").innerHTML = "Executable Name"')%> ExecRunning (Tests if executable is running)<br />
				<%= f.radio_button(:rule_type, "FileExists", :onclick => 'document.getElementById("param_label").innerHTML = "Path to File"')%> FileExists (Tests if a file exists)<br />
				<%= f.radio_button(:rule_type, "Custom", :onclick => 'document.getElementById("param_label").innerHTML = "Path to Executable"')%> Custom (Executes the file at the given path as a test)
			</td>
		</tr>
		<tr>
			<td><%= f.label(:rule_parameter, "", :id => "param_label") %></td>
			<td><%= text_field(:package_test, :rule_parameter)%></td>
		</tr>
		<tr>
			<td>Success On...</td>
			<td><%= f.radio_button(:success_value, true)%> True | <%= f.radio_button(:success_value, true)%> False</td>
		</tr>
	</table>
    <%= submit_tag "Create" %>
<% end %>

<%= link_to 'Back', @package %>

app/views/install_validations/show.html.erb
<h1>Package Test "<%= @package_test.name%>"</h1>
<h3>From Package <%= @package.name%></h3>

<table>
		<tr>
			<td>Description</td>
			<td><%= @package_test.description %></td>
		</tr>
		<tr>
			<td>Rule Type</td>
			<td><%= @package_test.rule_type %></td>
		</tr>
		<tr>
			<td>Parameter</td>
			<td><%= @package_test.rule_parameter%></td>
		</tr>
		<tr>
			<td>Success Value</td>
			<td><%= @package_test.success_value%></td>
		</tr>
</table>
<table>
	<tr>
		<th>Command</th>
		<th>Parameter</th>
		<th>#</th>
	</tr>
	<% @package_test.package_test_reactions.each do |ptr| %>
		<tr class="<%= cycle("even", "odd") %>">
			<td><%=ptr.command %></td>
			<td><%=ptr.parameter %></td>
			<td><%=ptr.repetitions %></td>
			<td><%= link_to 'Edit', edit_package_test_reaction_path(@package, @package_test, ptr) %></td>
    		<td><%= link_to 'Destroy', package_test_reaction_path(@package, @package_test, ptr), :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
	<% end %>
</table>	 
<%= link_to 'New Test Reaction', new_package_test_reaction_path(@package, @package_test)%>
<br />

<%= link_to 'Edit', edit_package_test_path(@package.id, @package_test.id) %>|
<%= link_to 'Back', package_path(@package) %>