config/routes.rb
Brunhilde::Application.routes.draw do |map|
  resources :computers do
    member do
      post :sort
      post :add_package
      post :add_configuration
      post :remove_configuration
    end
    resources :applied_configurations
  end

  resources :configurations do
    member do
      post :sort
      post :add_package
      post :remove_package
    end
    resources :applied_packages
  end
  resources :packages do
    resources :install_validations do
      resources :install_validation_reactions
    end
  end
  resources :user_sessions
  resources :users
  match ':controller/:action/:id.:format'
  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
	<title>Brunhilde</title>
	<link rel="shortcut icon" href="/favicon.ico" />
	
	<%= stylesheet_link_tag 'scaffold' %>
	<%= stylesheet_link_tag 'jqModal'%>
	<%= stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css'%>
	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js" %>
	<%= javascript_include_tag 'rails' %>
	<%= javascript_include_tag 'jqModal'%>
	<%= javascript_include_tag 'application'%>
	<%= javascript_include_tag 'http://www.netgrow.com.au/assets/files/jquery_plugins/jquery.dump.js' %>
	<%= csrf_meta_tag %>
</head>
<body>
<%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
<div id="header">
	<h1>Brunhilde 0.2.3ß</h1>
</div>
<div id="flash">
	<%= render :partial => "shared/flashes"%>
</div>
<div id="controller_tabs">
	<ul>
		<li <%= (@current_tab == "computers")? "class='active'" : ''%>>
			<%= link_to("Computers", computers_path) %>
		</li>
		<li <%= (@current_tab == "configurations")? "class='active'" : ''%>>
			<%= link_to("Configurations", configurations_path) %>
		</li>
		<li <%= (@current_tab == "packages")? "class='active'" : ''%>>
			<%= link_to("Packages", packages_path)%>
		</li>
	</ul>
</div>
<div id="main">
	<%= yield  %>
	
</div>

<%= yield :javascript %>
</body>
</html>